version: '3.6'

services:
  base:
    build:
      dockerfile: builder.dockerfile
      context: ./docker
      target: cmake-gcc
  aravis:
    restart: always
    network_mode: "host"
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_INDIRECT
    build:
      dockerfile: builder.dockerfile
      context: ./docker
      target: aravis-dev
    command: ["sleep", "infinity"]
    volumes:
      - .:/src
      - workspace:/home/vscode/workspace
  aravis-pi:
    restart: always
    network_mode: "host"
    devices:
     - "/dev/bus/usb:/dev/bus/usb"  # All USB devices
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_INDIRECT
    build:
      dockerfile: builder.rpi.dockerfile
      context: ./docker
      target: aravis-dev
    command: ["sleep", "infinity"]
    volumes:
      - .:/src
      - workspace:/home/vscode/workspace
  mvimpact:
    network_mode: "host"
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_INDIRECT
    build:
      dockerfile: builder.dockerfile
      context: ./docker
      target: mvIMPACT-dev
    volumes:
      - .:/src
      - workspace:/home/vscode/workspace
  aravis-deb:
    restart: always
    network_mode: "host"
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_INDIRECT
    build:
      dockerfile: aravis.dockerfile
      context: ./docker
    volumes:
      - .:/src
      - workspace:/workspace
  multi-sdk:
    restart: always
    network_mode: "host"
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_INDIRECT
    build:
      dockerfile: multi-sdk.dockerfile
      context: ./docker
    command: ["sleep", "infinity"]
    volumes:
      - .:/src
      - workspace:/home/vscode/workspace

volumes:
  workspace: