version: '3.6'

services:
  aravis:
    # Ensures when container crashes or host reboots, it should start up.
    restart: always
    network_mode: "host"  # Allows direct GigE access and X11 forwarding
    privileged: true # All USB devices, even when hotplugged
    environment:
    # These allow x11 forwarding if whomever starts the container has them set
      - DISPLAY
      - LIBGL_ALWAYS_INDIRECT
    build:
      dockerfile: builder.dockerfile
      context: ./docker
      target: aravis-dev
    # This ensures the current directory is installed in editable mode.
    command: [ "bash", "-c", "python3 -m pip install -e /src && sleep infinity"]
    volumes:
    # Using variables here allows them to be over-ridden, but have sane defaults
      - ${SRC_DIR:-.}:/src
      - ${OUTPUT_DIR:-/media/powerplant-sink/}:/output/
      - "/dev/bus/usb:/dev/bus/usb"  # All USB devices, even when hotplugged

  # This only makes sense if you can locate the Chronoptics SDK
  multi-sdk:
    restart: always
    network_mode: "host"
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_INDIRECT
    build:
      dockerfile: builder.dockerfile
      context: ./docker
      target: multi-sdk-dev
    command: [ "bash", "-c", "python3 -m pip install -e /src && sleep infinity"]
    volumes:
      - ${SRC_DIR:-.}:/src
      - ${OUTPUT_DIR:-/media/powerplant-sink/}:/output/

volumes:
  output: